Add release Job and docs

diff --git a/.github/workflows/Update.yml b/.github/workflows/Update.yml
--- a/.github/workflows/Update.yml
+++ b/.github/workflows/Update.yml
@@ -3,26 +3,20 @@
 
 name: Update Anduril
 
-# Controls when the workflow will run
 on:
   schedule:
-    # * is a special character in YAML so you have to quote this string
-    - cron:  '35 8,20 * * *' # min 35 to avoid beginning of the hour congestion 
+    - cron:  '35 8,20 * * *' # min 35 to avoid beginning of the hour congestion. 8am and 8pm
 
-  # Allows you to run this workflow manually from the Actions tab
+  # Allows manual trigger from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   Update-Check:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+      - name: Checkout Repo
+        uses: actions/checkout@v3
 
       - name: Pull from dependency cache  
         uses: awalsh128/cache-apt-pkgs-action@latest
@@ -33,33 +27,48 @@ jobs:
       - name: Install dependencies
         run: sudo apt install bzr
 
+      # get the revision number from launchpad and compare it to the last revision the repo has
       - name: Check for update 
         run: |
-
-
           [ -f ${{github.workspace}}/revno ]  && revnoExists="true" || revnoExists="false"
+
+          #if the repo has a revno file compare it to the latest revision on launchpad. if the revno file is missing we need to update
           [ "$revnoExists" == "true" ] && ( (( "$(cat ${{github.workspace}}/revno)" < "$(bzr revno lp:~toykeeper/flashlight-firmware/anduril2)" )) && update="true" || update="false") || update=true
 
+          #push update variable to github env
           echo "UPDATE=$update" >> $GITHUB_ENV
 
       - name: Get Change Info
         if: ${{env.UPDATE == 'true'}}
         run: |
           [ -f ${{github.workspace}}/revno ]  && revnoExists="true" || revnoExists="false"
+
+          #if the revno file exists calculate how many revisions are missing and pull all the change logs. if file is missing just get the latest change log
           gitmessage=$([ "$revnoExists" == "true" ] && (bzr log --short -l $(( "$(bzr revno lp:~toykeeper/flashlight-firmware/anduril2)" - "$(cat ${{github.workspace}}/revno)" )) lp:~toykeeper/flashlight-firmware/anduril2) || bzr log --short -l 1 lp:~toykeeper/flashlight-firmware/anduril2)
+
+          #write the newest revno to the revno file
           bzr revno lp:~toykeeper/flashlight-firmware/anduril2 > ${{github.workspace}}/revno
+
+          #create a random delimiter and send the multiline log messages to git env ending with the delimiter
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "GIT_MESSAGE<<$EOF" >> $GITHUB_ENV
           echo "$gitmessage" >> $GITHUB_ENV
           echo "$EOF" >> $GITHUB_ENV
 
+          #send the revno to git env for later use
+          echo "REVNO=$(bzr revno lp:~toykeeper/flashlight-firmware/anduril2)" >> $GITHUB_ENV
+
       - name: Pull-Toykeeper/Anduril2
         if: ${{env.UPDATE == 'true'}}
         run: |
           bzrRepositoryRoot=${{github.workspace}}/bzrTemp
-          mkdir $bzrRepositoryRoot
-          cd $bzrRepositoryRoot
+          mkdir "$bzrRepositoryRoot"
+          cd "$bzrRepositoryRoot" || exit
+
+          #pull the toykeeper/anduril2 branch from launchpad
           bzr branch lp:~toykeeper/flashlight-firmware/anduril2
+
+          #send bzr repo location to git env for later use
           echo "BZR_REPO_ROOT=$bzrRepositoryRoot" >> $GITHUB_ENV
 
       - name: Clean Repo
@@ -67,11 +76,22 @@ jobs:
         run: |
           bzrRepositoryRoot=${{env.BZR_REPO_ROOT}}
 
+          #remove directories and files listed in the CLEANLIST. all items in CLEANLIST are prepended with "$bzrRepositoryRoot"/anduril2/ToyKeeper/
           [ -f ${{github.workspace}}/CLEANLIST ] && xargs -a ${{github.workspace}}/CLEANLIST -I{} -d'\n' rm -rf "$bzrRepositoryRoot"/anduril2/ToyKeeper/{}
+
+          #update ./build-all.sh with the new bin folder location
           sed -i "s/..\/..\/..\/bin\/build.sh/..\/..\/bin\/build.sh/g" "$bzrRepositoryRoot"/anduril2/ToyKeeper/spaghetti-monster/anduril/build-all.sh
+
+          #add exit status if builds fail in build-all So the build workflow will function
           sed -i "s/echo \"FAIL:\$FAILED\"/echo \"FAIL:\$FAILED\"\n  exit 1/g" "$bzrRepositoryRoot"/anduril2/ToyKeeper/spaghetti-monster/anduril/build-all.sh
+
+          #move bin folder into ToyKeeper
           mv -f "$bzrRepositoryRoot"/anduril2/bin/ "$bzrRepositoryRoot"/anduril2/ToyKeeper/
-          mv -f "$bzrRepositoryRoot"/anduril2/ToyKeeper/spaghetti-monster/COPYING "$bzrRepositoryRoot"/LICENSE
+
+          #move license into ToyKeeper
+          mv -f "$bzrRepositoryRoot"/anduril2/ToyKeeper/spaghetti-monster/COPYING "$bzrRepositoryRoot"/anduril2/ToyKeeper/LICENSE
+
+          #copy cleaned up bzr repo to git repo root and delete temp files
           cd "$bzrRepositoryRoot"/anduril2/ToyKeeper/ || exit
           cp -rf ./* ${{github.workspace}}
           cd ${{github.workspace}} || exit #get out of the working directory before the rapture
@@ -83,3 +103,26 @@ jobs:
         with:
           message: ${{env.GIT_MESSAGE}}
           default_author: github_actions
+
+
+#create release so the build action is triggered
+  release:
+    if: ${{env.UPDATE == 'true'}}
+    needs: Update-Check
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.REVNO }}
+          release_name: Release ${{ env.REVNO }}
+          body: ${{ env.GIT_MESSAGE }}
+          draft: false
+          prerelease: false
